weights: yolov5s.pt
cfg: my_dates/mydata_5.yaml
data: my_dates/mydata.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 400
batch_size: 10
img_size:
- 384
- 384
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs\train\exp7
